#if !canImport(ObjectiveC)
    import XCTest

    extension Base2048Tests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__Base2048Tests = [
            ("testDecode", testDecode),
            ("testEncode", testEncode),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        [
            testCase(Base2048Tests.__allTests__Base2048Tests),
        ]
    }
#endif
